name: Daily Dominance Tweet

on:
  schedule:
    - cron: '0 * * * *'  # Every hour UTC
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install tweepy requests python-dotenv

      - name: Run bot
        run: python daily_dominance_bot.py

      - name: Commit updated last_dominance.txt
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_dominance.txt
          git commit -m "Update last_dominance.txt" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
